---
name: CI
on:
  - push
  - create
  - pull_request
jobs:
  deployment:
    services:
      ids: b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzc5NDE3ZmJjLTdkMmUtNDY4Zi1iMzA2LWI0MGFhODdhZDEyZi81ZDk2YTdkYy03YmQxLTExZWQtOTRmMC0xMjhiNDI4MTk0MjQ=
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
